#!/usr/bin/env bash
#
# MR Optimum Computing Unit Quick Reference
#
# Copy-paste commands for common tasks
#

echo "==============================================="
echo "  MR Optimum Computing Unit Quick Reference"
echo "==============================================="
echo ""

# ============================================================================
# SETUP
# ============================================================================

echo "1. SETUP - Configure credentials once"
echo "======================================="
echo ""
echo "# Set your credentials"
echo "export CLOUDMR_EMAIL=\"your@email.com\""
echo "export CLOUDMR_PASSWORD=\"your_password\""
echo "export CLOUDMR_API_URL=\"https://f41j488v7j.execute-api.us-east-1.amazonaws.com/Prod\""
echo ""
echo "# Save to file (never commit!)"
echo "cat > ~/.cloudmr_env << EOF"
echo "export CLOUDMR_EMAIL=\"your@email.com\""
echo "export CLOUDMR_PASSWORD=\"your_password\""
echo "export CLOUDMR_API_URL=\"https://f41j488v7j.execute-api.us-east-1.amazonaws.com/Prod\""
echo "EOF"
echo ""
echo "# Use it"
echo "source ~/.cloudmr_env"
echo ""

# ============================================================================
# REGISTRATION
# ============================================================================

echo ""
echo "2. REGISTRATION - Register computing unit (ONE TIME)"
echo "======================================================"
echo ""
echo "# Mode 1 (CloudMRHub Managed) - Recommended"
echo "source ~/.cloudmr_env"
echo "./scripts/register-computing-unit.sh"
echo ""
echo "# Mode 2 (User Owned)"
echo "source ~/.cloudmr_env"
echo "export MODE=\"mode_2\""
echo "./scripts/register-computing-unit.sh"
echo ""
echo "# With custom stack name"
echo "source ~/.cloudmr_env"
echo "export STACK_NAME=\"my-mroptimum-stack\""
echo "./scripts/register-computing-unit.sh"
echo ""

# ============================================================================
# JOB SUBMISSION
# ============================================================================

echo ""
echo "3. JOB SUBMISSION - Submit jobs (REPEATEDLY)"
echo "=============================================="
echo ""
echo "# Interactive (prompts for mode selection)"
echo "source ~/.cloudmr_env"
echo "./scripts/submit-job.sh"
echo ""
echo "# Mode 1 (CloudMRHub Managed)"
echo "source ~/.cloudmr_env"
echo "export MODE=\"mode_1\""
echo "./scripts/submit-job.sh"
echo ""
echo "# Mode 2 (User Owned)"
echo "source ~/.cloudmr_env"
echo "export MODE=\"mode_2\""
echo "./scripts/submit-job.sh"
echo ""
echo "# Specific computing unit ID"
echo "source ~/.cloudmr_env"
echo "export COMPUTING_UNIT_ID=\"550e8400-e29b-41d4-a716-446655440000\""
echo "./scripts/submit-job.sh"
echo ""
echo "# Non-interactive (for CI/CD)"
echo "source ~/.cloudmr_env"
echo "export MODE=\"mode_1\""
echo "export INTERACTIVE=\"false\""
echo "./scripts/submit-job.sh"
echo ""
echo "# Custom job name"
echo "source ~/.cloudmr_env"
echo "export PIPELINE_ALIAS=\"my-special-job-$(date +%s)\""
echo "./scripts/submit-job.sh"
echo ""

# ============================================================================
# MANUAL API CALLS
# ============================================================================

echo ""
echo "4. MANUAL API CALLS - For debugging"
echo "===================================="
echo ""
echo "# Get ID token"
echo "ID_TOKEN=\$(curl -s -X POST \\"
echo "  \"https://f41j488v7j.execute-api.us-east-1.amazonaws.com/Prod/api/auth/login\" \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"email\":\"your@email.com\",\"password\":\"your_password\"}' \\"
echo "  | jq -r '.id_token')"
echo ""
echo "# List computing units"
echo "curl -H \"Authorization: Bearer \$ID_TOKEN\" \\"
echo "  'https://f41j488v7j.execute-api.us-east-1.amazonaws.com/Prod/api/computing-unit/list?app_name=CAMRIE' \\"
echo "  | jq ."
echo ""
echo "# Register computing unit"
echo "curl -X POST \\"
echo "  'https://f41j488v7j.execute-api.us-east-1.amazonaws.com/Prod/api/computing-unit/register' \\"
echo "  -H \"Authorization: Bearer \$ID_TOKEN\" \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"appName\":\"MR Optimum\",\"mode\":\"mode_1\",\"provider\":\"cloudmrhub\",\"awsAccountId\":\"262361552878\",\"region\":\"us-east-1\",\"stateMachineArn\":\"arn:aws:states:us-east-1:...\"}' \\"
echo "  | jq ."
echo ""
echo "# Queue job (Pattern 1: by mode)"
echo "curl -X POST \\"
echo "  'https://f41j488v7j.execute-api.us-east-1.amazonaws.com/Prod/api/pipeline/queue_job' \\"
echo "  -H \"Authorization: Bearer \$ID_TOKEN\" \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"cloudapp_name\":\"CAMRIE\",\"alias\":\"my-job\",\"mode\":\"mode_1\",\"task\":{\"task_type\":\"brain_calculation\"}}' \\"
echo "  | jq ."
echo ""
echo "# Queue job (Pattern 2: by mode_2)"
echo "curl -X POST \\"
echo "  'https://f41j488v7j.execute-api.us-east-1.amazonaws.com/Prod/api/pipeline/queue_job' \\"
echo "  -H \"Authorization: Bearer \$ID_TOKEN\" \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"cloudapp_name\":\"CAMRIE\",\"alias\":\"my-job\",\"mode\":\"mode_2\",\"task\":{\"task_type\":\"brain_calculation\"}}' \\"
echo "  | jq ."
echo ""
echo "# Queue job (Pattern 3: by computing_unit_id)"
echo "curl -X POST \\"
echo "  'https://f41j488v7j.execute-api.us-east-1.amazonaws.com/Prod/api/pipeline/queue_job' \\"
echo "  -H \"Authorization: Bearer \$ID_TOKEN\" \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"cloudapp_name\":\"CAMRIE\",\"alias\":\"my-job\",\"computing_unit_id\":\"550e8400-e29b-41d4-a716-446655440000\",\"task\":{\"task_type\":\"brain_calculation\"}}' \\"
echo "  | jq ."
echo ""

# ============================================================================
# TROUBLESHOOTING
# ============================================================================

echo ""
echo "5. TROUBLESHOOTING - Debug commands"
echo "===================================="
echo ""
echo "# Check CloudFormation stack status"
echo "aws cloudformation describe-stacks --stack-name mroptimum-app --query 'Stacks[0].StackStatus'"
echo ""
echo "# Get stack outputs"
echo "aws cloudformation describe-stacks --stack-name mroptimum-app --query 'Stacks[0].Outputs' | jq ."
echo ""
echo "# Check State Machine"
echo "aws stepfunctions describe-state-machine --state-machine-arn 'arn:aws:states:us-east-1:262361552878:stateMachine:...'"
echo ""
echo "# Check job execution"
echo "aws stepfunctions describe-execution --execution-arn 'arn:aws:states:us-east-1:262361552878:execution:...'"
echo ""
echo "# Check Lambda logs"
echo "aws logs tail /aws/lambda/cloudmr-queuejob --follow"
echo ""
echo "# List jobs in S3"
echo "aws s3 ls cloudmr-data-cloudmrhub-brain-us-east-1/ --recursive"
echo ""
echo "# List results"
echo "aws s3 ls cloudmr-results-cloudmrhub-brain-us-east-1/ --recursive"
echo ""

# ============================================================================
# ENVIRONMENT VARIABLES REFERENCE
# ============================================================================

echo ""
echo "6. ENVIRONMENT VARIABLES - Full reference"
echo "=========================================="
echo ""
echo "Registration (register-computing-unit.sh):"
echo "  CLOUDMR_EMAIL         (required) CloudMR user email"
echo "  CLOUDMR_PASSWORD      (required) CloudMR user password"
echo "  CLOUDMR_API_URL       (required) CloudMR Brain API URL"
echo "  APP_NAME              (optional, default: MR Optimum)"
echo "  MODE                  (optional, default: mode_1)"
echo "  AWS_ACCOUNT_ID        (optional, auto-detect)"
echo "  STATE_MACHINE_ARN     (optional, auto-detect from CloudFormation)"
echo "  STACK_NAME            (optional, default: mroptimum-app)"
echo "  REGION                (optional, default: us-east-1)"
echo ""
echo "Job Submission (submit-job.sh):"
echo "  CLOUDMR_EMAIL         (required) CloudMR user email"
echo "  CLOUDMR_PASSWORD      (required) CloudMR user password"
echo "  CLOUDMR_API_URL       (required) CloudMR Brain API URL"
echo "  APP_NAME              (optional, default: CAMRIE)"
echo "  MODE                  (optional, selects mode_1 or mode_2)"
echo "  COMPUTING_UNIT_ID     (optional, selects specific unit)"
echo "  PIPELINE_ALIAS        (optional, default: auto-generated)"
echo "  TASK_DEFINITION       (optional, default: brain calculation)"
echo "  INTERACTIVE           (optional, default: true)"
echo ""

# ============================================================================
# WORKFLOW PATTERNS
# ============================================================================

echo ""
echo "7. WORKFLOW PATTERNS - Common use cases"
echo "========================================"
echo ""
echo "Pattern 1: One-off test"
echo "  1. Run register-computing-unit.sh"
echo "  2. Run submit-job.sh interactively"
echo ""
echo "Pattern 2: Automated CI/CD"
echo "  1. Register once (save in CI/CD secrets)"
echo "  2. Submit jobs with INTERACTIVE=false in pipeline"
echo ""
echo "Pattern 3: Multi-mode testing"
echo "  1. Register with mode_1"
echo "  2. Register with mode_2"
echo "  3. Submit jobs, select different modes"
echo ""
echo "Pattern 4: User-owned infrastructure (Mode 2)"
echo "  1. Deploy SAM stack to user AWS account"
echo "  2. Register with MODE=mode_2"
echo "  3. Submit jobs with MODE=mode_2"
echo ""

# ============================================================================
# QUICK START
# ============================================================================

echo ""
echo "8. QUICK START - Get running in 2 minutes"
echo "========================================"
echo ""
echo "source ~/.cloudmr_env"
echo "./scripts/register-computing-unit.sh && ./scripts/submit-job.sh"
echo ""

echo ""
echo "==============================================="
echo "  For full documentation see:"
echo "  COMPUTING-UNIT-WORKFLOW.md"
echo "==============================================="
