AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Parent template for the nested SAM applications.


Parameters:
  CortexHost: 
    Type: String
    Description: cm cortex
    Default: 'cancelit-env-1.eba-pmamcuv5.us-east-1.elasticbeanstalk.com'

  FargateImageUri:
    Type: String
    Description: >-
      URI of the Docker image for the Fargate task (must have been pushed
      to ECR already—e.g. "123456789012.dkr.ecr.us-east-1.amazonaws.com/run-job-fargate:latest").

  ECSClusterName:
    Type: String
    Default: run-job-cluster
    Description: "Name of the ECS cluster where the Fargate task will run."

  SubnetId1:
    Type: AWS::EC2::Subnet::Id
    Description: first public subnet
  SubnetId2:
    Type: AWS::EC2::Subnet::Id
    Description: second public subnet
  
  SecurityGroupIds:
    Type: AWS::EC2::SecurityGroup::Id
    Description: a single Security Group Id

  StageName:
    Type: String
    Default: Prod
    AllowedValues: [Prod, Dev, Test]
    Description: "Deployment stage for CalculationApp"


  LambdaImageUri:
    Type: String
    Description: "ECR URI of the pre-built Lambda image"

  DataBucketPName:
    Type: String
    Description: "Name of the Data Bucket (from cloudmr-brain)"

  ResultsBucketPName:
    Type: String
    Description: "Name of the Results Bucket (from cloudmr-brain)"

  FailedBucketPName:
    Type: String
    Description: "Name of the Failed Bucket (from cloudmr-brain)"

  TrustedAccountID:
    Type: String
    Description: "AWS Account ID of cloudmr-brain (Account B) that will invoke this app"
    Default: ""



Globals:
  Function:
    Timeout: 60
    MemorySize: 512
    Architectures:
    - x86_64
    Environment:
      Variables:
        Application: MR Optimum
        Host: !Ref CortexHost
        CloudMRApiUrl: !Sub https://${CortexHost}/api
        PipelineScheduler: !Sub https://${CortexHost}/api/pipeline/request
        PipelineCompleted: !Sub https://${CortexHost}/api/pipeline/completed
        PipelineFailed: !Sub https://${CortexHost}/api/pipeline/failed
        deleteDataAPI: !Sub https://${CortexHost}/api/data/delete 
        updateDataAPI: !Sub https://${CortexHost}/api/data/update 
        PipelineDeleteAPI: !Sub https://${CortexHost}/api/pipeline/delete
 
Resources:

  # DataBucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: !Sub "${AWS::StackName}-data"
  #     VersioningConfiguration:
  #       Status: Enabled
  #     LifecycleConfiguration:
  #       Rules:
  #         - Id: ArchiveData
  #           Status: Enabled
  #           ExpirationInDays: 365  # 1 years
  #     CorsConfiguration:
  #       CorsRules:
  #       - AllowedHeaders:
  #           - "*"
  #         AllowedMethods:
  #           - GET
  #           - PUT
  #           - HEAD
  #           - POST
  #           - DELETE
  #         AllowedOrigins:
  #           - "*"
  #         ExposedHeaders:
  #           - "ETag"

  #     PublicAccessBlockConfiguration:
  #       BlockPublicAcls: false
  #       BlockPublicPolicy: false
  #       IgnorePublicAcls: false
  #       RestrictPublicBuckets: false
  #     OwnershipControls:
  #       Rules:
  #       - ObjectOwnership: BucketOwnerPreferred

  # # this app is the one the routes the fialed bucket and the result bucket to cloudmr
  # ArkApp:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: ark/template.yaml
  #     Parameters:
  #       PipelineCompleted: !Sub "https://${CortexHost}/api/pipeline/completed"
  #       PipelineFailed: !Sub "https://${CortexHost}/api/pipeline/failed"
  #       PipelineScheduler: !Sub "https://${CortexHost}/api/pipeline/request"
  #       ResultsBucketPName: !Sub "${AWS::StackName}-results"
  #       FailedBucketPName: !Sub "${AWS::StackName}-failed"

  CalculationApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: calculation/template.yaml
      Parameters:                          # now pass the two IDs directly
        StageName:           !Ref StageName
        DataBucketPName:     !Ref DataBucketPName
        ResultsBucketPName:  !Ref ResultsBucketPName
        FailedBucketPName:   !Ref FailedBucketPName
        TrustedAccountID:    !Ref TrustedAccountID
        FargateImageUri:     !Ref FargateImageUri
        ECSClusterName:      !Ref ECSClusterName
        SubnetId1:           !Ref SubnetId1
        SubnetId2:           !Ref SubnetId2
        SecurityGroupIds:    !Ref SecurityGroupIds
        LambdaImageUri:      !Ref LambdaImageUri
        

  # APIApp:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: APIs/template.yaml
  #     Parameters:
  #       CortexHost: !Ref CortexHost
  #       StageName: !Ref StageName
  #       CalculationStateMachineARN: !GetAtt CalculationApp.Outputs.StateMachineArn

  # FrontendApp:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: frontend/template.yaml
  #     Parameters:
  #       CortexHost: !Ref CortexHost
  #       StageName: !Ref StageName
  #       ResultsBucketPName: !GetAtt ArkApp.Outputs.ResultsBucket
  #       FailedBucketPName: !GetAtt ArkApp.Outputs.FailedBucket
  #       DataBucketPName: !Ref DataBucket
  #       UserAuthorizerFunctionARN: !GetAtt APIApp.Outputs.UserAuthorizerFunctionARN
        
Outputs:
  CalculationStateMachineArn:
    Description: "ARN of the nested CalculationApp StateMachine"
    Value: !GetAtt CalculationApp.Outputs.StateMachineArn
  # QueueJobApiUrl:
  #   Description: "Queue-Job API endpoint URL"
  #   Value: !GetAtt APIApp.Outputs.QueueJobApiUrl
  #   Export:
  #     Name: !Sub "${AWS::StackName}-QueueJobApiUrl"
  
  # QueueJobApiKeyID:
  #   Description: "API Key for Queue-Job API"
  #   Value: !GetAtt APIApp.Outputs.QueueJobApiKeyID

  # DeleteJobApi:
  #   Description: "API Gateway endpoint URL for Delete function"
  #   Value: !GetAtt FrontendApp.Outputs.DeleteJobApi
  #   Export:
  #     Name: !Sub "${AWS::StackName}-DeleteJobApi"

  # GetZipApi:
  #   Description: "API Gateway endpoint URL for GetZip function"
  #   Value: !GetAtt FrontendApp.Outputs.GetZipApi
  #   Export:
  #     Name: !Sub "${AWS::StackName}-GetZipApi"

  # DataReadApi:
  #   Description: "API Gateway endpoint URL for DataRead function"
  #   Value: !GetAtt FrontendApp.Outputs.DataReadApi
  #   Export:
  #     Name: !Sub "${AWS::StackName}-DataReadApi"

  # DeleteFileApi:
  #   Description: "API Gateway endpoint URL for DeleteFile function"
  #   Value: !GetAtt FrontendApp.Outputs.DeleteFileApi
  #   Export:
  #     Name: !Sub "${AWS::StackName}-DeleteFileApi"

  # UpdateFileApi:
  #   Description: "API Gateway endpoint URL for UpdateFile function"
  #   Value: !GetAtt FrontendApp.Outputs.UpdateFileApi
  #   Export:
  #     Name: !Sub "${AWS::StackName}-UpdateFileApi"

  # UploadRequestApi:
  #   Description: "API Gateway endpoint URL for UploadRequest function"
  #   Value: !GetAtt FrontendApp.Outputs.UploadRequestApi
  #   Export:
  #     Name: !Sub "${AWS::StackName}-UploadRequestApi"

  # UploadInitiateApi:
  #   Description: "API Gateway endpoint URL for UploadInitiate function"
  #   Value: !GetAtt FrontendApp.Outputs.UploadInitiateApi
  #   Export:
  #     Name: !Sub "${AWS::StackName}-UploadInitiateApi"

  # DownloadRequestApi:
  #   Description: "API Gateway endpoint URL for DownloadRequest function"
  #   Value: !GetAtt FrontendApp.Outputs.DownloadRequestApi
  #   Export:
  #     Name: !Sub "${AWS::StackName}-DownloadRequestApi"

  # UploadFinalizeApi:
  #   Description: "API Gateway endpoint URL for UploadFinalize function"
  #   Value: !GetAtt FrontendApp.Outputs.UploadFinalizeApi
  #   Export:
  #     Name: !Sub "${AWS::StackName}-UploadFinalizeApi"

  # UploadResultsInitiateApi:
  #   Description: "API Gateway endpoint URL for UploadResultsInitiate function"
  #   Value: !GetAtt FrontendApp.Outputs.UploadResultsInitiateApi
  #   Export:
  #     Name: !Sub "${AWS::StackName}-UploadResultsInitiateApi"

  # UploadResultsFinalizeApi:
  #   Description: "API Gateway endpoint URL for UploadResultsFinalize function"
  #   Value: !GetAtt FrontendApp.Outputs.UploadResultsFinalizeApi
  #   Export:
  #     Name: !Sub "${AWS::StackName}-UploadResultsFinalizeApi"

  # FrontendAPI:
  #   Description: "Base API Gateway endpoint URL for Frontend"
  #   Value: !GetAtt FrontendApp.Outputs.FrontendAPI
  #   Export:
  #     Name: !Sub "${AWS::StackName}-FrontendAPI"

