AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Parent template for the nested SAM applications.


Parameters:
  CortexHost: 
    Type: String
    Description: cm cortex
    Default: 'cancelit-env-1.eba-pmamcuv5.us-east-1.elasticbeanstalk.com'

  FargateImageUri:
    Type: String
    Description: >-
      URI of the Docker image for the Fargate task (must have been pushed
      to ECR already—e.g. "123456789012.dkr.ecr.us-east-1.amazonaws.com/run-job-fargate:latest").

  ECSClusterName:
    Type: String
    Default: run-job-cluster
    Description: "Name of the ECS cluster where the Fargate task will run."

  SubnetId1:
    Type: AWS::EC2::Subnet::Id
    Description: first public subnet
  SubnetId2:
    Type: AWS::EC2::Subnet::Id
    Description: second public subnet
  
  SecurityGroupIds:
    Type: AWS::EC2::SecurityGroup::Id
    Description: a single Security Group Id

  StageName:
    Type: String
    Default: Prod
    AllowedValues: [Prod, Dev, Test]
    Description: "Deployment stage for CalculationApp"


  LambdaImageUri:
    Type: String
    Description: "ECR URI of the pre-built Lambda image"



Globals:
  Function:
    Timeout: 60
    MemorySize: 512
    Architectures:
    - x86_64
    Environment:
      Variables:
        Application: MR Optimum
        Host: !Ref CortexHost
        CloudMRApiUrl: !Sub https://${CortexHost}/api
        PipelineScheduler: !Sub https://${CortexHost}/api/pipeline/request
        PipelineCompleted: !Sub https://${CortexHost}/api/pipeline/completed
        PipelineFailed: !Sub https://${CortexHost}/api/pipeline/failed
        deleteDataAPI: !Sub https://${CortexHost}/api/data/delete 
        updateDataAPI: !Sub https://${CortexHost}/api/data/update 
        PipelineDeleteAPI: !Sub https://${CortexHost}/api/pipeline/delete



 
Resources:

  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-data"
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ArchiveData
            Status: Enabled
            ExpirationInDays: 365  # 1 years
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
            - "*"
          AllowedMethods:
            - GET
            - PUT
            - HEAD
            - POST
            - DELETE
          AllowedOrigins:
            - "*"
          ExposedHeaders:
            - "ETag"

      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
        - ObjectOwnership: BucketOwnerPreferred

  # this app is the one the routes the fialed bucket and the reuslt bucket to cloudmr
  ArkApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: ark/template.yaml
      Parameters:
        PipelineCompleted: !Sub "https://${CortexHost}/api/pipeline/completed"
        PipelineFailed: !Sub "https://${CortexHost}/api/pipeline/failed"
        PipelineScheduler: !Sub "https://${CortexHost}/api/pipeline/request"
        ResultsBucketPName: !Sub "${AWS::StackName}-results"
        FailedBucketPName: !Sub "${AWS::StackName}-failed"

  CalculationApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: calculation/template.yaml
      Parameters:                          # now pass the two IDs directly
        CortexHost:          !Ref CortexHost
        StageName:           !Ref StageName
        DataBucketPName:      !Ref DataBucket
        ResultsBucketPName:  !Sub "${AWS::StackName}-results"
        FailedBucketPName:   !Sub "${AWS::StackName}-failed"
        FargateImageUri:     !Ref FargateImageUri
        ECSClusterName:      !Ref ECSClusterName
        SubnetId1:           !Ref SubnetId1
        SubnetId2:           !Ref SubnetId2
        SecurityGroupIds:    !Ref SecurityGroupIds
        LambdaImageUri:      !Ref LambdaImageUri
        

  APIApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: APIs/template.yaml
      Parameters:
        CortexHost: !Ref CortexHost
        StageName: !Ref StageName
        CalculationStateMachineARN: !GetAtt CalculationApp.Outputs.StateMachineArn

Outputs:
  CalculationStateMachineArn:
    Description: "ARN of the nested CalculationApp StateMachine"
    Value: !GetAtt CalculationApp.Outputs.StateMachineArn
  QueueJobApiUrl:
    Description: "Queue-Job API endpoint URL"
    Value: !GetAtt APIApp.Outputs.QueueJobApiUrl
    Export:
      Name: !Sub "${AWS::StackName}-QueueJobApiUrl"


  # ResultsBucketName:
  #   Description: "Name of the S3 bucket for results"
  #   Value: !GetAtt ArkApp.Outputs.ResultsBucket
  # FailedBucketName:
  #   Description: "Name of the S3 bucket for failed jobs"
  #   Value: !GetAtt ArkApp.Outputs.FailedBucket

  QueueJobApiKeyID:
    Description: "API Key for Queue-Job API"
    Value: !GetAtt APIApp.Outputs.QueueJobApiKeyID
  
