AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template that reorders resources to avoid circular dependency without enforcing bucket names.



Parameters:
  ResultsBucketPName:
    Type: String
    Description: "The fixed name for the Results bucket"
    Default: "camrie-results"
  FailedBucketPName:
    Type: String
    Description: "The fixed name for the Failed bucket"
    Default: "camrie-failed"
  PipelineCompleted:
    Type: String
    Description: API endpoint for pipeline completed
  PipelineFailed:
    Type: String
    Description: API endpoint for pipeline failed
  PipelineScheduler:
    Type: String
    Description: API endpoint for pipeline scheduler

Globals:
  Function:
    Environment:
      Variables:
        PipelineCompleted: !Ref PipelineCompleted
        PipelineFailed: !Ref PipelineFailed
        PipelineScheduler: !Ref PipelineScheduler
        Application: MR Optimum

Resources:


  ResultsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref ResultsBucketPName
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - HEAD
              - POST
              - DELETE
            AllowedOrigins:
              - "*"
            ExposedHeaders:
              - "ETag"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      LifecycleConfiguration:
        Rules:
          - Id: DeleteUnzippedObjects
            Status: Enabled
            ExpirationInDays: 7
            Prefix: unzipped/

  FailedBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref FailedBucketPName
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - HEAD
              - POST
              - DELETE
            AllowedOrigins:
              - "*"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred


  UpdateJobFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: >
        This function updates Cloudmrhub after Mroptium computation.
        It is triggered when an object is created in the results bucket.
      PackageType: Zip
      CodeUri: .
      Handler: app.lambda_handler
      Runtime: python3.9
      MemorySize: 512
      Timeout: 60
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref ResultsBucketPName
        - S3FullAccessPolicy:
            BucketName: !Ref FailedBucketPName
      Environment:
        Variables:
          ResultsBucket: !Ref ResultsBucketPName
          FailedBucket: !Ref FailedBucketPName
          PipelineCompleted: !Ref PipelineCompleted
          PipelineFailed: !Ref PipelineFailed
          PipelineScheduler: !Ref PipelineScheduler
          Application: CAMRIE

         
      Events:
        S3ResultsEvent:
          Type: S3
          Properties:
            Bucket: !Ref ResultsBucket
            Events: s3:ObjectCreated:*
        S3ResultsEventFailed:
          Type: S3
          Properties:
            Bucket: !Ref FailedBucket
            Events: s3:ObjectCreated:*

Outputs:
  ResultsBucket:
    Description: "Name of the Results bucket"
    Value: !Ref ResultsBucket
    Export:
      Name: !Sub "${AWS::StackName}-ResultsBucket"

  FailedBucket:
    Description: "Name of the Failed bucket"
    Value: !Ref FailedBucket
    Export:
      Name: !Sub "${AWS::StackName}-FailedBucket"


# same stack !GetAtt ArkApp.Outputs.FailedBucket

#cross stack !ImportValue mroptimum-app-test-ResultsBucket
